spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.154.85/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
server:
    context-path: /sell
#    port: 8080

##配置Logback
#logging:
#  pattern:
#    console: "%d - %msg%n"  #配置日志的格式
#  level: debug     #日志的级别


